### ISSUE TITLE
Update frontend-platform's react-router version

### ISSUE THREAD

**Issue by muselesscreator** [openedx/wg-frontend#153]
We are currently a major version behind in fronten-platform's version of react-router.  The new version includes a number of helpful features (plus is where all of the documentation now defaults), but is a breaking change.

https://reactrouter.com/en/main/upgrading/v5

```[tasklist]
### Subtasks
- [ ] https://github.com/openedx/frontend-platform/pull/422
- [ ] https://github.com/openedx/frontend-app-publisher/pull/850
- [ ] https://github.com/openedx/frontend-app-support-tools/pull/313
- [ ] https://github.com/openedx/frontend-lib-special-exams/pull/90
- [ ] https://github.com/openedx/frontend-app-ecommerce/pull/268
- [ ] https://github.com/openedx/frontend-app-learner-dashboard/pull/126
- [ ] https://github.com/openedx/frontend-component-footer/pull/275
- [ ] https://github.com/openedx/frontend-app-gradebook/pull/319
- [ ] https://github.com/edx/frontend-component-header-edx/pull/359
- [ ] https://github.com/openedx/frontend-app-ora-grading/pull/174
- [ ] https://github.com/edx/frontend-component-footer-edx/pull/258
- [ ] https://github.com/openedx/frontend-template-application/pull/558
- [ ] https://github.com/openedx/frontend-component-header/pull/316
- [ ] https://github.com/openedx/frontend-app-payment/pull/722
- [ ] https://github.com/openedx/frontend-app-account/pull/793
- [ ] https://github.com/openedx/frontend-lib-content-components/pull/280
- [ ] https://github.com/openedx/frontend-app-learner-record/pull/150
- [ ] https://github.com/openedx/frontend-app-enterprise-public-catalog/pull/314
- [ ] https://github.com/openedx/frontend-app-learner-portal-programs/pull/272
- [ ] https://github.com/openedx/frontend-app-program-console/pull/106
- [ ] https://github.com/openedx/frontend-app-profile/pull/716
- [ ] https://github.com/openedx/frontend-app-communications/pull/122
- [ ] frontend-app-authn: blocked.  See [spreadsheet](https://docs.google.com/spreadsheets/d/1vUtp-ykv1tgw_a_qUWnJwhTc9KqkYlI1mNAvlSq9SZQ/edit#gid=0&range=D4)
- [ ] frontend-app-course-authoring: blocked.  See [spreadsheet](https://docs.google.com/spreadsheets/d/1vUtp-ykv1tgw_a_qUWnJwhTc9KqkYlI1mNAvlSq9SZQ/edit#gid=0&range=D13). 
- [ ] frontend-app-discussions: blocked.  See [spreadsheet](https://docs.google.com/spreadsheets/d/1vUtp-ykv1tgw_a_qUWnJwhTc9KqkYlI1mNAvlSq9SZQ/edit#gid=0&range=D16).
- [ ] frontend-app-learner-portal-enterprise: blocked.  See [spreadsheet](https://docs.google.com/spreadsheets/d/1vUtp-ykv1tgw_a_qUWnJwhTc9KqkYlI1mNAvlSq9SZQ/edit#gid=0&range=D22).
- [ ] frontend-app-library-authoring: blocked.  See [spreadsheet](https://docs.google.com/spreadsheets/d/1vUtp-ykv1tgw_a_qUWnJwhTc9KqkYlI1mNAvlSq9SZQ/edit#gid=0&range=D23).
- [ ] frontend-app-admin-portal: blocked.  See [spreadsheet](https://docs.google.com/spreadsheets/d/1vUtp-ykv1tgw_a_qUWnJwhTc9KqkYlI1mNAvlSq9SZQ/edit#gid=0&range=D28).
- [ ] frontend-app-learning: blocked.  See [spreadsheet](https://docs.google.com/spreadsheets/d/1vUtp-ykv1tgw_a_qUWnJwhTc9KqkYlI1mNAvlSq9SZQ/edit#gid=0&range=D29).
```

**Comment by arbrandes** [comment]
@abdullahwaheed, can we get a few details on why this is blocked?

**Comment by abdullahwaheed** [comment]
@arbrandes its not blocked now. Its our next planned major upgrade, [here](https://github.com/openedx/frontend-platform/pull/422) is frontend-platform PR for this, we were just waiting node 18 to wrap up to unblock its PRs. [Here](https://docs.google.com/spreadsheets/d/1vUtp-ykv1tgw_a_qUWnJwhTc9KqkYlI1mNAvlSq9SZQ/edit?usp=sharing)  is the sheet we are maintaining for its progress.
